version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    target-branch: development
    schedule:
      interval: cron
      cronjob: "0 0 * * sun%2"
    open-pull-requests-limit: 10
    labels:
      - Dependencies
    commit-message:
      include: scope

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: development
    schedule:
      interval: cron
      cronjob: "0 0 * * sun%2"
    labels:
      - Dependencies
    commit-message:
      include: scope
