#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Commit test init...'

# Running Prettier standards
npx prettier --write . ||
(
    echo '🛑✋ Write Prettier errors found.';
    false;
)

# Check Prettier standards
npm run check-format ||
(
    echo '🛑✋ Styling errors found.';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
    echo '🛑✋ Lint errors found.';
    false;
)

# TypeScript type check
npm run check-types ||
(
    echo '🛑✋ Type errors found.';
    false;
)

# Unit tests check
npm test ||
(
    echo '🛑✋ Unit tests errors found.';
    false;
)

# If everything passes... Now we can commit
echo '✔️✔️✔️ Style, Lint, Types and Unit test has pass. Initiating NextJS build ⚙️...'

npm run build ||
(
    echo '❌ Build failed. Aborting commit.';
    false;
)

# If everything passes... Now we can commit
echo '✔️✔️✔️✔️ All test passed! Go ahead and push your commit 🚀'
