#!/bin/sh

echo '🏗️👷 Commit test init...'

# Running Prettier standards, then re-stage tracked files
if ! npx prettier --write .; then
  echo '🛑✋ Write Prettier errors found.'
  exit 1
fi
git add -u

# Check Prettier standards
npm run check-format ||
(
    echo '🛑✋ Styling errors found.';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
    echo '🛑✋ Lint errors found.';
    false;
)

# Unit tests check
npm test ||
(
    echo '🛑✋ Unit tests errors found.';
    false;
)

# If everything passes... Now we can commit
echo '✔️✔️✔️ Style, Lint, Types and Unit test has pass. Initiating NextJS build ⚙️...'

npm run build ||
(
    echo '❌ Build failed. Aborting commit.';
    false;
)

# If everything passes... Now we can commit
echo '✔️✔️✔️✔️ All test passed! Go ahead and push your commit 🚀'

# Running Prettier standards, then re-stage tracked files
if ! npx prettier --write .; then
  echo '🛑✋ Write Prettier errors found.'
  exit 1
fi
git add -u

# Check Prettier standards
npm run check-format ||
(
    echo '🛑✋ Styling errors found.';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
    echo '🛑✋ Lint errors found.';
    false;
)

# Unit tests check
npm test ||
(
    echo '🛑✋ Unit tests errors found.';
    false;
)

# If everything passes... Now we can commit
echo '✔️✔️✔️ Style, Lint, Types and Unit test has pass. Initiating NextJS build ⚙️...'

npm run build ||
(
    echo '❌ Build failed. Aborting commit.';
    false;
)

# If everything passes... Now we can commit
echo '✔️✔️✔️✔️ All test passed! Go ahead and push your commit 🚀'
